### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/MTPipeline#77]
#### Data
- [ ] Write a new Make rule for non-planet data
- [x] Run the imaging pipeline on all the non-planet data
- [x] Consult with Max on gathering non-WFPC2 data
#### Ephemerides
- [ ] Refactor `build_master_images.py` with bulk inserts 
- [ ] Replace CGI/TELNET with `pexpect` in `build_master_images.py`
- [ ] Run ephemerides pipeline on Jupiter
- [ ] Fix incorrect database data; dump and rebuild if performance is good enough.
- [ ] Set up production ST database instance.
#### Testing
- [x] Set up Travis for CI
- [ ] Develop a testing plan for legacy code
#### Docs
- [ ] Create GitHub Pages for docs
- [ ] Setup Sphinx
- [ ] Create Sphinx to GitHub Pages Makefile rule
